[package]
name = "cdp_client"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = { version = "2.2.0", features = ["json"] }
tungstenite = "0.16.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }